version: '3.18'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/env/node.env
    container_name: camagru_nodejs
